# Generated by Django 4.0.5 on 2024-01-15 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ing', models.CharField(max_length=128)),
                ('presentacion_ing', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('direccion', models.TextField()),
                ('telefono_ofi', models.CharField(max_length=20)),
                ('correo_ofi', models.EmailField(max_length=254)),
                ('horario_atencion', models.TextField()),
                ('nombre_contacto', models.CharField(max_length=128)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.AddField(
            model_name='producto',
            name='insumos_herramientas',
            field=models.TextField(default='null'),
        ),
        migrations.CreateModel(
            name='ProveedorIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.ingrediente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_ingrediente', models.CharField(max_length=128)),
                ('cantidad_ingrediente', models.FloatField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.ingrediente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
    ]
