# Generated by Django 4.0.5 on 2024-01-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_ingrediente_proveedor_remove_producto_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='nombre_ing',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='presentacion_ing',
            new_name='presentacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='cod_prod',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_prod',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='producto',
            name='insumos_herramientas',
            field=models.TextField(default=''),
        ),
    ]
