# Generated by Django 4.0.5 on 2024-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_nombre_ing_ingrediente_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoingrediente',
            name='unidad_ingrediente',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidad_receta',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
