# Generated by Django 5.0.1 on 2024-01-28 23:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0003_producto_imgagen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="imgagen",
            new_name="imagen",
        ),
    ]
