# Generated by Django 5.0.1 on 2024-02-07 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0004_rename_imgagen_producto_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subtipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="subtipo",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="productos.subtipo",
            ),
        ),
        migrations.AddField(
            model_name="subtipo",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="productos.tipo"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="productos.tipo",
            ),
        ),
    ]
